# Generated by Django 4.1.5 on 2023-03-26 17:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('login', '0002_product_info_product_id_product_info_product_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='order_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, max_length=200, null=True)),
                ('product_description', models.CharField(blank=True, max_length=200, null=True)),
                ('product_price', models.CharField(blank=True, max_length=200, null=True)),
                ('product_id', models.CharField(blank=True, max_length=200, null=True)),
                ('product_unit', models.IntegerField(blank=True, null=True)),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='OrderImage')),
                ('product_status', models.IntegerField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product_info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='login.product_info')),
            ],
        ),
    ]
