# Generated by Django 4.1.5 on 2023-03-26 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_order_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_info',
            name='product_status',
        ),
        migrations.AddField(
            model_name='order_info',
            name='order_status',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
